WALLETS_ALWAYS_COPY = [
    "9Rqb3Nvru6Mjtnf8wWh9YFe5dqfeLbGXL6vCn8DdCvTg",
    "BQ9BX1fnN2e2ByskRAybiw21MPtJLUpDY191Cgq3LyKp"
]

USE_AXIOM_FOR_FILTERED_WALLETS = True
ENABLE_REAL_TRADING = True
DAILY_SPEND_LIMIT_USD = 30